version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: orders
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    networks:
      - orders

  order-service:
    build: ./order-service
    container_name: order_service
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:orders@db:5432/orders
      - FLASK_APP=app
      - FLASK_ENV=development
      - ORDER_SERVICE_URL=http://order-service:5000
    ports:
      - "5001:5000"
    command: ["/bin/sh", "-c", "flask db upgrade && flask run --host=0.0.0.0"]
    networks:
      - orders

  inventory-service:
    build: ./inventory-service
    container_name: inventory_service
    restart: always
    depends_on:
      - db
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - INVENTORY_SERVICE_URL=http://inventory-service:5000
    ports:
      - "5002:5000"
    networks:
      - orders

  gateway:
    build: ./gateway
    container_name: gateway_service
    restart: always
    depends_on:
      - order-service
    environment:
      FLASK_ENV: development
      GATEWAY_SERVICE_URL: http://gateway-service:5000
    ports:
      - "5000:5000"
    networks:
      - orders

volumes:
  orders_data:
networks:
  orders:  
    driver: bridge
